CMAKE_MINIMUM_REQUIRED(VERSION 3.5)
SET(PRJ mxfs-macos)
PROJECT(${PRJ} C CXX)

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -o0 -g")
SET(CMAKE_C_FLAGS "${CMAKE_CXX_FLAGS} -o0 -g")
SET(CMAKE_INCLUDE_CURRENT_DIR ON)

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D__DRIVER_INFO__ -D__DRIVER_DEBUG__")
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D__DRIVER_INFO__ -D__DRIVER_DEBUG__")


LINK_DIRECTORIES("/usr/local/lib/")
LINK_DIRECTORIES("/usr/lib/")
INCLUDE_DIRECTORIES("/usr/local/include/")
INCLUDE_DIRECTORIES("/usr/include/")
INCLUDE_DIRECTORIES("../../inc")
INCLUDE_DIRECTORIES("../../src/drivers/inc")
INCLUDE_DIRECTORIES("../../src/drivers/macos")

FILE(GLOB C_SOURCE_FILES ../../src/*.cc)
FILE(GLOB C_SOURCE_TEST_FILES ../../src/test/*.cc)
FILE(GLOB C_SOURCE_DRIVER_FILES ../../src/drivers/macos/*.cc)

LIST(REMOVE_ITEM C_SOURCE_TEST_FILES "${CMAKE_CURRENT_SOURCE_DIR}/../../src/test/rp2040.cc")


ADD_EXECUTABLE(
    ${PRJ}
    ${C_SOURCE_TEST_FILES}
    ${C_SOURCE_FILES}
    ${C_SOURCE_DRIVER_FILES}
)
TARGET_LINK_LIBRARIES(${PRJ} m)
TARGET_LINK_LIBRARIES(${PRJ} gtest_main gtest pthread)

SET_TARGET_PROPERTIES(
    ${PRJ}
    PROPERTIES
    CXX_STANDARD 17
)

