CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
SET(PRJ formatter)
PROJECT(${PRJ} C CXX)

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0 -g")
SET(CMAKE_C_FLAGS "${CMAKE_CXX_FLAGS} -O0 -g")
#SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -o3")
SET(CMAKE_INCLUDE_CURRENT_DIR ON)

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DUSE_WIRINGPI_LIB")
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DUSE_WIRINGPI_LIB")

LINK_DIRECTORIES("/usr/local/lib/")
LINK_DIRECTORIES("/usr/lib/")
INCLUDE_DIRECTORIES("/usr/local/include/")
INCLUDE_DIRECTORIES("/usr/include/")
INCLUDE_DIRECTORIES("../../inc")
LINK_DIRECTORIES("/opt/vc/lib/")
INCLUDE_DIRECTORIES("/opt/vc/include/")

FILE(GLOB C_SOURCE_FILES ../../src/*.cc)
# LIST(REMOVE_ITEM C_SOURCE_FILES "${CMAKE_CURRENT_SOURCE_DIR}/../../src/test+gpio.cc")

ADD_EXECUTABLE(
    ${PRJ}
    ${C_SOURCE_FILES}
    ${FONT_SOURCE_FILES}
)
TARGET_LINK_LIBRARIES(${PRJ} m)
TARGET_LINK_LIBRARIES(${PRJ} bcm_host)

SET_TARGET_PROPERTIES(
    ${PRJ}
    PROPERTIES
    CXX_STANDARD 17
)

